[client/catapult] fix: catapult build failing on Windows problem: catapult build failing on Windows with this error error C3493: 'Num_Open_Attempts' cannot be implicitly captured because no default capture mode has been specified solution: add Num_Open_Attempts to the capture list